server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /escapezone

#spring:
#  datasource:
#    url:

---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/dev
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: prod

